# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.08, name: PAD_1},
    {id: 1, size: 0.08, name: PAD_2},
    {id: 2, size: 0.08, name: PAD_3},
    {id: 3, size: 0.08, name: PAD_4},
    {id: 4, size: 0.08, name: PAD_5},
    {id: 5, size: 0.08, name: NORTH},
    {id: 6, size: 0.08, name: SOUTH},
    {id: 7, size: 0.08, name: EAST}
 ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: '_80mm_bundle',
      layout:
        [
          {id: 2, size: 0.08, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 0, size: 0.08, x: -0.0423, y: 0.0849, z: -0.0023, qw: 0.9997, qx: -0.0176, qy: -0.0194, qz: -0.0020},
          {id: 1, size: 0.08, x: 0.0423, y: 0.0847, z: -0.0011, qw: 0.9998, qx: -0.0204, qy: 0.0088, qz: 0.0005},
          {id: 5, size: 0.08, x: -0.0425, y: -0.0848, z: -0.0015, qw: 0.9999, qx: 0.0104, qy: -0.0071, qz: -0.0015},
          {id: 6, size: 0.08, x: 0.0423, y: -0.0847, z: -0.0004, qw: 0.9999, qx: 0.0156, qy: 0.0037, qz: 0.0007}
        ]
    }
  ]
