set(_CATKIN_CURRENT_PACKAGE "ore_detection")
set(ore_detection_VERSION "0.0.0")
set(ore_detection_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(ore_detection_PACKAGE_FORMAT "2")
set(ore_detection_BUILD_DEPENDS "roscpp")
set(ore_detection_BUILD_EXPORT_DEPENDS "roscpp")
set(ore_detection_BUILDTOOL_DEPENDS "catkin")
set(ore_detection_BUILDTOOL_EXPORT_DEPENDS )
set(ore_detection_EXEC_DEPENDS "roscpp")
set(ore_detection_RUN_DEPENDS "roscpp")
set(ore_detection_TEST_DEPENDS )
set(ore_detection_DOC_DEPENDS )
set(ore_detection_URL_WEBSITE "")
set(ore_detection_URL_BUGTRACKER "")
set(ore_detection_URL_REPOSITORY "")
set(ore_detection_DEPRECATED "")