set(_CATKIN_CURRENT_PACKAGE "mining_map")
set(mining_map_VERSION "0.0.0")
set(mining_map_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(mining_map_PACKAGE_FORMAT "2")
set(mining_map_BUILD_DEPENDS "roscpp" "geometry_msgs" "visualization_msgs")
set(mining_map_BUILD_EXPORT_DEPENDS "roscpp")
set(mining_map_BUILDTOOL_DEPENDS "catkin")
set(mining_map_BUILDTOOL_EXPORT_DEPENDS )
set(mining_map_EXEC_DEPENDS "roscpp" "geometry_msgs" "visualization_msgs")
set(mining_map_RUN_DEPENDS "roscpp" "geometry_msgs" "visualization_msgs")
set(mining_map_TEST_DEPENDS )
set(mining_map_DOC_DEPENDS )
set(mining_map_URL_WEBSITE "")
set(mining_map_URL_BUGTRACKER "")
set(mining_map_URL_REPOSITORY "")
set(mining_map_DEPRECATED "")