set(_CATKIN_CURRENT_PACKAGE "ieee_master")
set(ieee_master_VERSION "0.0.0")
set(ieee_master_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(ieee_master_PACKAGE_FORMAT "2")
set(ieee_master_BUILD_DEPENDS "roscpp")
set(ieee_master_BUILD_EXPORT_DEPENDS "roscpp")
set(ieee_master_BUILDTOOL_DEPENDS "catkin")
set(ieee_master_BUILDTOOL_EXPORT_DEPENDS )
set(ieee_master_EXEC_DEPENDS "roscpp")
set(ieee_master_RUN_DEPENDS "roscpp")
set(ieee_master_TEST_DEPENDS )
set(ieee_master_DOC_DEPENDS )
set(ieee_master_URL_WEBSITE "")
set(ieee_master_URL_BUGTRACKER "")
set(ieee_master_URL_REPOSITORY "")
set(ieee_master_DEPRECATED "")