set(_CATKIN_CURRENT_PACKAGE "tof_sensors")
set(tof_sensors_VERSION "0.0.0")
set(tof_sensors_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(tof_sensors_PACKAGE_FORMAT "2")
set(tof_sensors_BUILD_DEPENDS "roscpp" "serial" "std_msgs")
set(tof_sensors_BUILD_EXPORT_DEPENDS "roscpp" "serial" "std_msgs")
set(tof_sensors_BUILDTOOL_DEPENDS "catkin")
set(tof_sensors_BUILDTOOL_EXPORT_DEPENDS )
set(tof_sensors_EXEC_DEPENDS "roscpp" "serial" "std_msgs")
set(tof_sensors_RUN_DEPENDS "roscpp" "serial" "std_msgs")
set(tof_sensors_TEST_DEPENDS )
set(tof_sensors_DOC_DEPENDS )
set(tof_sensors_URL_WEBSITE "")
set(tof_sensors_URL_BUGTRACKER "")
set(tof_sensors_URL_REPOSITORY "")
set(tof_sensors_DEPRECATED "")