// Generated by gencpp from file april_tag_detection/GetAprilTag.msg
// DO NOT EDIT!


#ifndef APRIL_TAG_DETECTION_MESSAGE_GETAPRILTAG_H
#define APRIL_TAG_DETECTION_MESSAGE_GETAPRILTAG_H

#include <ros/service_traits.h>


#include <april_tag_detection/GetAprilTagRequest.h>
#include <april_tag_detection/GetAprilTagResponse.h>


namespace april_tag_detection
{

struct GetAprilTag
{

typedef GetAprilTagRequest Request;
typedef GetAprilTagResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAprilTag
} // namespace april_tag_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::april_tag_detection::GetAprilTag > {
  static const char* value()
  {
    return "8da4d9ec9691782775e0aa5067c83359";
  }

  static const char* value(const ::april_tag_detection::GetAprilTag&) { return value(); }
};

template<>
struct DataType< ::april_tag_detection::GetAprilTag > {
  static const char* value()
  {
    return "april_tag_detection/GetAprilTag";
  }

  static const char* value(const ::april_tag_detection::GetAprilTag&) { return value(); }
};


// service_traits::MD5Sum< ::april_tag_detection::GetAprilTagRequest> should match
// service_traits::MD5Sum< ::april_tag_detection::GetAprilTag >
template<>
struct MD5Sum< ::april_tag_detection::GetAprilTagRequest>
{
  static const char* value()
  {
    return MD5Sum< ::april_tag_detection::GetAprilTag >::value();
  }
  static const char* value(const ::april_tag_detection::GetAprilTagRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::april_tag_detection::GetAprilTagRequest> should match
// service_traits::DataType< ::april_tag_detection::GetAprilTag >
template<>
struct DataType< ::april_tag_detection::GetAprilTagRequest>
{
  static const char* value()
  {
    return DataType< ::april_tag_detection::GetAprilTag >::value();
  }
  static const char* value(const ::april_tag_detection::GetAprilTagRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::april_tag_detection::GetAprilTagResponse> should match
// service_traits::MD5Sum< ::april_tag_detection::GetAprilTag >
template<>
struct MD5Sum< ::april_tag_detection::GetAprilTagResponse>
{
  static const char* value()
  {
    return MD5Sum< ::april_tag_detection::GetAprilTag >::value();
  }
  static const char* value(const ::april_tag_detection::GetAprilTagResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::april_tag_detection::GetAprilTagResponse> should match
// service_traits::DataType< ::april_tag_detection::GetAprilTag >
template<>
struct DataType< ::april_tag_detection::GetAprilTagResponse>
{
  static const char* value()
  {
    return DataType< ::april_tag_detection::GetAprilTag >::value();
  }
  static const char* value(const ::april_tag_detection::GetAprilTagResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APRIL_TAG_DETECTION_MESSAGE_GETAPRILTAG_H
