// Generated by gencpp from file april_tag_detection/GetAprilTagRequest.msg
// DO NOT EDIT!


#ifndef APRIL_TAG_DETECTION_MESSAGE_GETAPRILTAGREQUEST_H
#define APRIL_TAG_DETECTION_MESSAGE_GETAPRILTAGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace april_tag_detection
{
template <class ContainerAllocator>
struct GetAprilTagRequest_
{
  typedef GetAprilTagRequest_<ContainerAllocator> Type;

  GetAprilTagRequest_()
    : tag_id()
    , cam_id()  {
    }
  GetAprilTagRequest_(const ContainerAllocator& _alloc)
    : tag_id(_alloc)
    , cam_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _tag_id_type;
  _tag_id_type tag_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cam_id_type;
  _cam_id_type cam_id;





  typedef boost::shared_ptr< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetAprilTagRequest_

typedef ::april_tag_detection::GetAprilTagRequest_<std::allocator<void> > GetAprilTagRequest;

typedef boost::shared_ptr< ::april_tag_detection::GetAprilTagRequest > GetAprilTagRequestPtr;
typedef boost::shared_ptr< ::april_tag_detection::GetAprilTagRequest const> GetAprilTagRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator1> & lhs, const ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tag_id == rhs.tag_id &&
    lhs.cam_id == rhs.cam_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator1> & lhs, const ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace april_tag_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e850c675d61239dfbb5e7f7d9441439";
  }

  static const char* value(const ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e850c675d61239dULL;
  static const uint64_t static_value2 = 0xfbb5e7f7d9441439ULL;
};

template<class ContainerAllocator>
struct DataType< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "april_tag_detection/GetAprilTagRequest";
  }

  static const char* value(const ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string tag_id\n"
"string cam_id\n"
;
  }

  static const char* value(const ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tag_id);
      stream.next(m.cam_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAprilTagRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::april_tag_detection::GetAprilTagRequest_<ContainerAllocator>& v)
  {
    s << indent << "tag_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.tag_id);
    s << indent << "cam_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cam_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APRIL_TAG_DETECTION_MESSAGE_GETAPRILTAGREQUEST_H
