// Generated by gencpp from file april_tag_detection/GetAprilTagResponse.msg
// DO NOT EDIT!


#ifndef APRIL_TAG_DETECTION_MESSAGE_GETAPRILTAGRESPONSE_H
#define APRIL_TAG_DETECTION_MESSAGE_GETAPRILTAGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace april_tag_detection
{
template <class ContainerAllocator>
struct GetAprilTagResponse_
{
  typedef GetAprilTagResponse_<ContainerAllocator> Type;

  GetAprilTagResponse_()
    : tag_count(0)
    , tag_id()
    , cam_id()
    , poses()  {
    }
  GetAprilTagResponse_(const ContainerAllocator& _alloc)
    : tag_count(0)
    , tag_id(_alloc)
    , cam_id(_alloc)
    , poses(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _tag_count_type;
  _tag_count_type tag_count;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _tag_id_type;
  _tag_id_type tag_id;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _cam_id_type;
  _cam_id_type cam_id;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAprilTagResponse_

typedef ::april_tag_detection::GetAprilTagResponse_<std::allocator<void> > GetAprilTagResponse;

typedef boost::shared_ptr< ::april_tag_detection::GetAprilTagResponse > GetAprilTagResponsePtr;
typedef boost::shared_ptr< ::april_tag_detection::GetAprilTagResponse const> GetAprilTagResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator1> & lhs, const ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator2> & rhs)
{
  return lhs.tag_count == rhs.tag_count &&
    lhs.tag_id == rhs.tag_id &&
    lhs.cam_id == rhs.cam_id &&
    lhs.poses == rhs.poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator1> & lhs, const ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace april_tag_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a747909d241398506309a0b18c8aa9eb";
  }

  static const char* value(const ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa747909d24139850ULL;
  static const uint64_t static_value2 = 0x6309a0b18c8aa9ebULL;
};

template<class ContainerAllocator>
struct DataType< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "april_tag_detection/GetAprilTagResponse";
  }

  static const char* value(const ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 tag_count\n"
"uint8[] tag_id\n"
"uint8[] cam_id\n"
"geometry_msgs/Pose[] poses\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tag_count);
      stream.next(m.tag_id);
      stream.next(m.cam_id);
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAprilTagResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::april_tag_detection::GetAprilTagResponse_<ContainerAllocator>& v)
  {
    s << indent << "tag_count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tag_count);
    s << indent << "tag_id[]" << std::endl;
    for (size_t i = 0; i < v.tag_id.size(); ++i)
    {
      s << indent << "  tag_id[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.tag_id[i]);
    }
    s << indent << "cam_id[]" << std::endl;
    for (size_t i = 0; i < v.cam_id.size(); ++i)
    {
      s << indent << "  cam_id[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.cam_id[i]);
    }
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // APRIL_TAG_DETECTION_MESSAGE_GETAPRILTAGRESPONSE_H
