set(_CATKIN_CURRENT_PACKAGE "april_tag_detection")
set(april_tag_detection_VERSION "0.0.0")
set(april_tag_detection_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(april_tag_detection_PACKAGE_FORMAT "2")
set(april_tag_detection_BUILD_DEPENDS "apriltag_ros" "roscpp")
set(april_tag_detection_BUILD_EXPORT_DEPENDS "apriltag_ros" "roscpp")
set(april_tag_detection_BUILDTOOL_DEPENDS "catkin")
set(april_tag_detection_BUILDTOOL_EXPORT_DEPENDS )
set(april_tag_detection_EXEC_DEPENDS "apriltag_ros" "roscpp")
set(april_tag_detection_RUN_DEPENDS "apriltag_ros" "roscpp")
set(april_tag_detection_TEST_DEPENDS )
set(april_tag_detection_DOC_DEPENDS )
set(april_tag_detection_URL_WEBSITE "")
set(april_tag_detection_URL_BUGTRACKER "")
set(april_tag_detection_URL_REPOSITORY "")
set(april_tag_detection_DEPRECATED "")