set(_CATKIN_CURRENT_PACKAGE "mecanum_odometry")
set(mecanum_odometry_VERSION "0.0.0")
set(mecanum_odometry_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(mecanum_odometry_PACKAGE_FORMAT "2")
set(mecanum_odometry_BUILD_DEPENDS "roscpp")
set(mecanum_odometry_BUILD_EXPORT_DEPENDS "roscpp")
set(mecanum_odometry_BUILDTOOL_DEPENDS "catkin")
set(mecanum_odometry_BUILDTOOL_EXPORT_DEPENDS )
set(mecanum_odometry_EXEC_DEPENDS "roscpp")
set(mecanum_odometry_RUN_DEPENDS "roscpp")
set(mecanum_odometry_TEST_DEPENDS )
set(mecanum_odometry_DOC_DEPENDS )
set(mecanum_odometry_URL_WEBSITE "")
set(mecanum_odometry_URL_BUGTRACKER "")
set(mecanum_odometry_URL_REPOSITORY "")
set(mecanum_odometry_DEPRECATED "")