set(_CATKIN_CURRENT_PACKAGE "map_example")
set(map_example_VERSION "0.0.0")
set(map_example_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(map_example_PACKAGE_FORMAT "2")
set(map_example_BUILD_DEPENDS "mining_map" "roscpp" "interactive_markers")
set(map_example_BUILD_EXPORT_DEPENDS "mining_map" "roscpp")
set(map_example_BUILDTOOL_DEPENDS "catkin")
set(map_example_BUILDTOOL_EXPORT_DEPENDS )
set(map_example_EXEC_DEPENDS "mining_map" "roscpp" "interactive_markers")
set(map_example_RUN_DEPENDS "mining_map" "roscpp" "interactive_markers")
set(map_example_TEST_DEPENDS )
set(map_example_DOC_DEPENDS )
set(map_example_URL_WEBSITE "")
set(map_example_URL_BUGTRACKER "")
set(map_example_URL_REPOSITORY "")
set(map_example_DEPRECATED "")