set(_CATKIN_CURRENT_PACKAGE "apriltag_tf")
set(apriltag_tf_VERSION "0.0.0")
set(apriltag_tf_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(apriltag_tf_PACKAGE_FORMAT "2")
set(apriltag_tf_BUILD_DEPENDS "roscpp" "tf2_ros" "apriltag_ros" "keyboard")
set(apriltag_tf_BUILD_EXPORT_DEPENDS "roscpp" "tf2_ros")
set(apriltag_tf_BUILDTOOL_DEPENDS "catkin")
set(apriltag_tf_BUILDTOOL_EXPORT_DEPENDS )
set(apriltag_tf_EXEC_DEPENDS "roscpp" "tf2_ros" "apriltag_ros" "keyboard")
set(apriltag_tf_RUN_DEPENDS "roscpp" "tf2_ros" "apriltag_ros" "keyboard")
set(apriltag_tf_TEST_DEPENDS )
set(apriltag_tf_DOC_DEPENDS )
set(apriltag_tf_URL_WEBSITE "")
set(apriltag_tf_URL_BUGTRACKER "")
set(apriltag_tf_URL_REPOSITORY "")
set(apriltag_tf_DEPRECATED "")