// Generated by gencpp from file mecanum_ik/EmptySrv.msg
// DO NOT EDIT!


#ifndef MECANUM_IK_MESSAGE_EMPTYSRV_H
#define MECANUM_IK_MESSAGE_EMPTYSRV_H

#include <ros/service_traits.h>


#include <mecanum_ik/EmptySrvRequest.h>
#include <mecanum_ik/EmptySrvResponse.h>


namespace mecanum_ik
{

struct EmptySrv
{

typedef EmptySrvRequest Request;
typedef EmptySrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EmptySrv
} // namespace mecanum_ik


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mecanum_ik::EmptySrv > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::mecanum_ik::EmptySrv&) { return value(); }
};

template<>
struct DataType< ::mecanum_ik::EmptySrv > {
  static const char* value()
  {
    return "mecanum_ik/EmptySrv";
  }

  static const char* value(const ::mecanum_ik::EmptySrv&) { return value(); }
};


// service_traits::MD5Sum< ::mecanum_ik::EmptySrvRequest> should match
// service_traits::MD5Sum< ::mecanum_ik::EmptySrv >
template<>
struct MD5Sum< ::mecanum_ik::EmptySrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mecanum_ik::EmptySrv >::value();
  }
  static const char* value(const ::mecanum_ik::EmptySrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mecanum_ik::EmptySrvRequest> should match
// service_traits::DataType< ::mecanum_ik::EmptySrv >
template<>
struct DataType< ::mecanum_ik::EmptySrvRequest>
{
  static const char* value()
  {
    return DataType< ::mecanum_ik::EmptySrv >::value();
  }
  static const char* value(const ::mecanum_ik::EmptySrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mecanum_ik::EmptySrvResponse> should match
// service_traits::MD5Sum< ::mecanum_ik::EmptySrv >
template<>
struct MD5Sum< ::mecanum_ik::EmptySrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mecanum_ik::EmptySrv >::value();
  }
  static const char* value(const ::mecanum_ik::EmptySrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mecanum_ik::EmptySrvResponse> should match
// service_traits::DataType< ::mecanum_ik::EmptySrv >
template<>
struct DataType< ::mecanum_ik::EmptySrvResponse>
{
  static const char* value()
  {
    return DataType< ::mecanum_ik::EmptySrv >::value();
  }
  static const char* value(const ::mecanum_ik::EmptySrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MECANUM_IK_MESSAGE_EMPTYSRV_H
