// Generated by gencpp from file mecanum_ik/EmptySrvRequest.msg
// DO NOT EDIT!


#ifndef MECANUM_IK_MESSAGE_EMPTYSRVREQUEST_H
#define MECANUM_IK_MESSAGE_EMPTYSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mecanum_ik
{
template <class ContainerAllocator>
struct EmptySrvRequest_
{
  typedef EmptySrvRequest_<ContainerAllocator> Type;

  EmptySrvRequest_()
    {
    }
  EmptySrvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EmptySrvRequest_

typedef ::mecanum_ik::EmptySrvRequest_<std::allocator<void> > EmptySrvRequest;

typedef boost::shared_ptr< ::mecanum_ik::EmptySrvRequest > EmptySrvRequestPtr;
typedef boost::shared_ptr< ::mecanum_ik::EmptySrvRequest const> EmptySrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace mecanum_ik

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::mecanum_ik::EmptySrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mecanum_ik/EmptySrvRequest";
  }

  static const char* value(const ::mecanum_ik::EmptySrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Empty service, no request and response\n"
;
  }

  static const char* value(const ::mecanum_ik::EmptySrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmptySrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mecanum_ik::EmptySrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mecanum_ik::EmptySrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MECANUM_IK_MESSAGE_EMPTYSRVREQUEST_H
