set(_CATKIN_CURRENT_PACKAGE "chassis_base")
set(chassis_base_VERSION "0.0.0")
set(chassis_base_MAINTAINER "Spacemaster85 <fusion2urdf@prosystem24.de>")
set(chassis_base_PACKAGE_FORMAT "2")
set(chassis_base_BUILD_DEPENDS "rospy")
set(chassis_base_BUILD_EXPORT_DEPENDS "rospy")
set(chassis_base_BUILDTOOL_DEPENDS "catkin")
set(chassis_base_BUILDTOOL_EXPORT_DEPENDS )
set(chassis_base_EXEC_DEPENDS "rospy")
set(chassis_base_RUN_DEPENDS "rospy")
set(chassis_base_TEST_DEPENDS )
set(chassis_base_DOC_DEPENDS )
set(chassis_base_URL_WEBSITE "")
set(chassis_base_URL_BUGTRACKER "")
set(chassis_base_URL_REPOSITORY "")
set(chassis_base_DEPRECATED "")